
import "./../globals.css";

import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import Header from "../Componenet/Header";
import Footer from "../Componenet/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params}) {
   const { locale } =await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
          
          <NextIntlClientProvider lang={locale}>
             <Header/>
            {children}
            <Footer/>
          </NextIntlClientProvider>
  );
}


